services:
  db:
    image: postgres:17-alpine
    container_name: ehalisaha-db
    environment:
      POSTGRES_DB: ehalisaha
      POSTGRES_USER: ehalisaha
      POSTGRES_PASSWORD: ehalisaha
    ports:
      - "5433:5432"   # host:5433 -> container:5432
    volumes:
      - ehalisaha_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  adminer:
    image: adminer:4
    container_name: ehalisaha-adminer
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"

  app:
    dns:
      - 1.1.1.1
      - 8.8.8.8
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ehalisaha-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ehalisaha
      SPRING_DATASOURCE_USERNAME: ehalisaha
      SPRING_DATASOURCE_PASSWORD: ehalisaha

      # ✅ Flyway kapalı: şemayı JPA/Hibernate yönetsin
      SPRING_FLYWAY_ENABLED: "false"

      # ✅ JPA tabloları oluştursun/güncellesin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      # (opsiyonel) log/SQL görmek istersen aç
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  ehalisaha_pgdata:
